[package]
name = "av-scenechange"
version = "0.1.0"
authors = ["Josh Holmer <jholmer.in@gmail.com>"]
edition = "2018"
description = "Estimates frames in a video where a scenecut would be ideal"
license = "MIT"
repository = "https://github.com/rust-av/av-scenechange"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
y4m = "0.4.0"
num-traits = "0.2.9"
clap = { version = "2.33.0", optional = true }
serde = { version = "1.0.102", optional = true }
serde_json = { version = "1.0.41", optional = true }

[features]
default = ["binary"]
binary = ["clap", "serde", "serde_json"]

[[bin]]
name = "av-scenechange"
path = "src/main.rs"
required-features = ["binary"]
